CREATE TABLE IF NOT EXISTS OWNERS (
    OWNER_ID BIGINT NOT NULL,
    OWNER_EMAIL VARCHAR(255),
    OWNER_NAME VARCHAR(255),
    OWNER_BUSINESS_NUMBER VARCHAR(255),
    OWNER_IS_DELETED BOOLEAN,
    PRIMARY KEY (OWNER_ID)
);

CREATE TABLE IF NOT EXISTS TOTAL_SALES_PER_DAY (
    totalSalesPerDayId BIGINT NOT NULL AUTO_INCREMENT,
    STORE_ID BIGINT NOT NULL,
    DATE DATE NOT NULL,
    DAILY_SALES INT NOT NULL,
    PRIMARY KEY (totalSalesPerDayId)
);

CREATE TABLE IF NOT EXISTS TOTAL_SALES_PER_MONTH (
    totalSalesPerMonthId BIGINT NOT NULL AUTO_INCREMENT,
    STORE_ID BIGINT NOT NULL,
    MONTH DATE NOT NULL,
    MONTH_SALES BIGINT NOT NULL,
    PRIMARY KEY (totalSalesPerMonthId)
);
